# # Python package
# # Create and test a Python package on multiple Python versions.
# # Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/python

# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest
# strategy:
#   matrix:
#     Python27:
#       python.version: '2.7'
#     Python35:
#       python.version: '3.5'
#     Python36:
#       python.version: '3.6'
#     Python37:
#       python.version: '3.7'

# steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#   displayName: 'Use Python $(python.version)'

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'
pool: name: Azure Pipelines steps: - task: UsePythonVersion@0 displayName: 'Use Python 3.10.6' inputs: versionSpec: 3.10.6 - script: | pip install selenium==4.12.0 pip install pytest pip install pytest-html pip install pytest-xdist pip install pytest-nunit displayName: 'Install Plugins' - script: 'pytest -rA --html=.\reports\Report.html --self-contained-html --doctest-modules --nunitxml=nunit/test-results.xml -n 5 --browsername %browser%' displayName: 'Run Python Tests' - task: PublishPipelineArtifact@1 displayName: 'Publish Pipeline Artifact'
